### ISSUE TITLE
Questions about the future

### ISSUE THREAD

**Issue by farnoy** [mcschroeder/ttrie#2]
Hey, great project! I'm wondering about a few things:
- Is the API going to change? Any new operations planned, or does it have to stay similar to keep those nice properties?
- Is it a problem, in practice, that keys stay in memory after deletion? Is the memory requirement large there?

Have you posted it on reddit or somewhere? I'm sure the community would appreciate it.

**Comment by mcschroeder** [comment]
Thank you for your interest, I appreciate it! As to your questions:
- I consider the API stable. One could think about maybe adding convenience methods like `null` or `adjust`. Stuff like `map` or `fold` would be more tricky, as I currently don't see a way to implement these in a contention-free manner in a transactional setting. Even though the concurrent trie, on which the transactional trie is based, does have an O(1) atomic snapshot operation (see [1]), I'm not sure if it's possible to combine this with STM. But I also haven't really looked into that very hard. Certainly an interesting little research topic.
- I don't think `delete` not compacting the trie should be a problem in practice. I've discussed this a little bit in my thesis [2]: just think of the common use case of mapping user IDs to users. When deleting a user, you'd usually wan't to keep a record of the key anyway, so as not to reuse it. Might as well leave the key in the trie. 
  But in any case, according to the benchmarks, the memory overhead of not deleting the keys and not compacting the trie appears to be negligible. Especially when compared to the memory consumption of a `TVar (HashMap a)`, which is up to 10 times larger when performing lots of transactions at once.
- I have not posted anything on Reddit yet, but it should be in the next Haskell Communities and Activities Report. Feel free to spread the word though!

If you're using this library, I'd love to hear about your experiences with it, and if the performance in your setting indeed matches the benchmarks.

[1] ["Concurrent Tries with Efficient Non-Blocking Snapshots"](https://axel22.github.io/resources/docs/ctries-snapshot.pdf) by Prokopec, Bronson, Bagwell and Odersky.

[2] ["Durability and Contention in Software Transactional Memory"](https://github.com/mcschroeder/thesis) (esp. chapter 3)

**Comment by farnoy** [comment]
Thanks for the answers!

I think the library is applicable for a lot of usecases already. Having snapshotted iteration where the transaction does not get restarted when someone else modifies those keys could be useful too. I think documenting or prefixing with `unsafe` would be enough, same as other functions. Correct me if I'm wrong, but if you could retrieve all the keys from the atomic snapshot then the only uncertain thing would be what keys you're getting, lookups would remain nice and atomic? This would be quite convenient to have.

I want to use the library, but I don't really have a need for performance there. There's little contention, I'll probably implement it just to move away from `TVar (Data.Map.Map k v)`.

**Comment by mcschroeder** [comment]
Hm, I'm not quite sure I understand the operation you propose.

But, generally speaking, an atomic snapshot operation (independent of STM) could only give you the state of the current physical structure of the trie, which might not reflect it's logical structure (due to the trie not compacting after deletion etc). Finding out if a key is really present in the map might incur a `readTVar` and thus entangle that key with the transaction. Iterating over all keys thus seems impractical.

**Comment by farnoy** [comment]
I see, it would not be as useful then.

Anyway, thanks for your answers and good luck in the future!
